version: "3.9"
# volumes:
#   - users_data
#   - widgets_data

services:
  web_frontend:
    build:
      context: web_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_USERS_API_URL=http://localhost:8000
      - REACT_APP_WIDGETS_API_URL=http://localhost:8001
    volumes:
      - ./web_frontend:/app

  users_service:
    build:
      context: ./users_service
      dockerfile: Dockerfile.dev
      args:
        DATABASE_URL: $DATABASE_URL
    ports:
      - "8000:8000"
    volumes:
      - ./users_service:/app
    environment:
      - WEB_FRONTEND_DOMAIN=http://localhost:3000
      - DATABASE_URL={DATABASE_URL}
      
  # users_db:
  #   image: postgres:15.1-bullseye

  widgets_service:
    build:
      context: ./widgets_service
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./widgets_service:/app
    environment:
      - WEB_FRONTEND_DOMAIN=http://localhost:3000
      - DATABASE_URL=postgres://jamesrogers:@localhost:5432/aws_learning_crud_mvp_widgets
  # widgets_db:
  #   image: postgres:15.1-bullseye
