version: "3.9"
volumes:
  users_db:
    external: true
  widgets_db:
    external: true

services:
# fe
  web_frontend:
    build:
      context: web_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_USERS_API_URL=http://localhost:8000
      - REACT_APP_WIDGETS_API_URL=http://localhost:8001
    volumes:
      - ./web_frontend:/app

# users
  users_service:
    build:
      context: ./users_service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./users_service:/app
    environment:
      - WEB_FRONTEND_DOMAIN=http://localhost:3000
      - DATABASE_URL=postgresql://postgres:postgres@users_db:5432/users

  users_db:
    image: postgres:15.1-bullseye
    volumes:
      - users_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=users

# widgets
  widgets_service:
    build:
      context: ./widgets_service
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./widgets_service:/app
    environment:
      - WEB_FRONTEND_DOMAIN=http://localhost:3000
      - DATABASE_URL=postgresql://postgres:postgres@widgets_db:5432/widgets

  widgets_db:
    image: postgres:15.1-bullseye
    volumes:
      - widgets_db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=widgets
