FROM node:19.4-bullseye
WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install

COPY index.js index.js
COPY migrations migrations

EXPOSE 8000
CMD ["npm", "run", "watch"]
